In [2]:
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.impute import SimpleImputer
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import SGDClassifier, LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
import numpy as np

In [3]:
df_train = pd.read_csv("titanic_train.csv")
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [5]:
df_train.drop(["Cabin","Ticket","Name"], axis =1, inplace = True)

In [6]:
df_test = pd.read_csv("titanic_test.csv")

In [7]:
# df_train["Embarked"].fillna("Q", inplace = True)
df_train["Embarked"].replace({"Q" : 0, "S" : 1, "C" : 3}, inplace = True)
df_train["Sex"].replace({"male": 0, "female" : 1}, inplace = True)
df_test["Embarked"].replace({"Q" : 0, "S" : 1, "C" : 3}, inplace = True)
df_test["Sex"].replace({"male": 0, "female" : 1}, inplace = True)

In [8]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    int64  
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Fare         891 non-null    float64
 8   Embarked     889 non-null    float64
dtypes: float64(3), int64(6)
memory usage: 62.8 KB


In [9]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy = "mean")),
])


In [10]:
num_cols = list(df_train)
full_pipeline = ColumnTransformer([
    ("num", num_pipeline, num_cols)
])
df_train_final_n = full_pipeline.fit_transform(df_train)

In [11]:
df_train_final = pd.DataFrame(df_train_final_n, columns = df_train.columns, index = df_train.index)
df_train_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    float64
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    float64
 3   Sex          891 non-null    float64
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    float64
 6   Parch        891 non-null    float64
 7   Fare         891 non-null    float64
 8   Embarked     891 non-null    float64
dtypes: float64(9)
memory usage: 62.8 KB


In [12]:
x_val = df_train_final.drop(["Survived"], axis = 1, inplace = False)
y_val = df_train_final["Survived"]

In [13]:
y_val.head()

0    0.0
1    1.0
2    1.0
3    1.0
4    0.0
Name: Survived, dtype: float64

In [14]:
l_svc = LinearSVC()
l_params = {'penalty': ("l1","l2"), 'C': [1,10]}
l_clf = GridSearchCV(l_svc, l_params)
l_clf.fit(x_val, y_val)
l_clf.best_params_

C:\Users\jeeva\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jeeva\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jeeva\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jeeva\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jeeva\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jeeva\AppData\Roaming\Python\Python3

{'C': 10, 'penalty': 'l2'}

In [15]:
l_svc_1 = LinearSVC(C = 1, penalty = 'l2')
l_svc_1.fit(x_val, y_val)
scores = cross_val_score(l_svc_1, x_val, y_val, cv = 5)
print(scores)

C:\Users\jeeva\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jeeva\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jeeva\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


[0.68715084 0.44382022 0.73595506 0.7247191  0.78651685]


C:\Users\jeeva\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jeeva\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\jeeva\AppData\Roaming\Python\Python310\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [16]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    int64  
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    int64  
dtypes: float64(2), int64(6), object(3)
memory usage: 36.0+ KB


In [17]:
poly_params = {'degree': [1,3], 'C': [1,10]}
poly_SVC = SVC(kernel = 'poly')
p_clf = GridSearchCV(poly_SVC, poly_params)
p_clf.fit(x_val, y_val)
p_clf.best_params_


{'C': 10, 'degree': 1}

In [18]:
poly_svc = SVC(kernel = 'poly', degree = 1, C = 1)
poly_svc.fit(x_val, y_val)
scores = cross_val_score(poly_svc, x_val, y_val, cv = 5)
print(scores)

[0.62011173 0.64606742 0.60674157 0.64044944 0.66292135]


In [19]:
x_val.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          1.0     3.0  0.0  22.0    1.0    0.0   7.2500       1.0
1          2.0     1.0  1.0  38.0    1.0    0.0  71.2833       3.0
2          3.0     3.0  1.0  26.0    0.0    0.0   7.9250       1.0
3          4.0     1.0  1.0  35.0    1.0    0.0  53.1000       1.0
4          5.0     3.0  0.0  35.0    0.0    0.0   8.0500       1.0

In [20]:
x_val.drop(['PassengerId'], axis = 1, inplace = True)
np.mean(x_val)

C:\Users\jeeva\AppData\Roaming\Python\Python310\site-packages\numpy\core\fromnumeric.py:3472: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


Pclass       2.308642
Sex          0.352413
Age         29.699118
SibSp        0.523008
Parch        0.381594
Fare        32.204208
Embarked     1.291339
dtype: float64

In [21]:
x_zero_mean_d = x_val - np.mean(x_val)
scalar = StandardScaler()
x_zero_mean_n = scalar.fit_transform(x_zero_mean_d)
x_zero_mean = pd.DataFrame(x_zero_mean_n, columns = x_zero_mean_d.columns, index =x_zero_mean_d.index)
x_zero_mean.head()

Pclass       Sex       Age     SibSp     Parch      Fare  Embarked
0  0.827377 -0.737695 -0.592481  0.432793 -0.473674 -0.502445 -0.335084
1 -1.566107  1.355574  0.638789  0.432793 -0.473674  0.786845  1.965224
2  0.827377  1.355574 -0.284663 -0.474545 -0.473674 -0.488854 -0.335084
3 -1.566107  1.355574  0.407926  0.432793 -0.473674  0.420730 -0.335084
4  0.827377 -0.737695  0.407926 -0.474545 -0.473674 -0.486337 -0.335084

In [22]:
SGD_C = SGDClassifier()
SC_params = {'penalty': ('l1','l2')}
SC_clf = GridSearchCV(SGD_C, SC_params)
SC_clf.fit(x_zero_mean, y_val)
SC_clf.best_params_

{'penalty': 'l1'}

In [23]:
SGD_C = SGDClassifier(loss = 'log', penalty = 'l1')
SGD_C.fit(x_zero_mean, y_val)
scores = cross_val_score(SGD_C, x_zero_mean, y_val, cv = 5)
print(scores)

[0.81005587 0.73595506 0.7752809  0.75280899 0.76966292]


In [24]:
RFC = RandomForestClassifier(n_estimators = 500, n_jobs = -1)

In [25]:
RFC.fit(x_zero_mean, y_val)
scores = cross_val_score(RFC, x_zero_mean, y_val, cv = 5)
print(scores)

[0.77653631 0.80898876 0.85393258 0.76404494 0.83146067]


In [26]:
print(RFC.feature_importances_)
print(RFC.feature_names_in_)

[0.08369432 0.26027152 0.26268449 0.04912053 0.03820906 0.27100599
 0.03501409]
['Pclass' 'Sex' 'Age' 'SibSp' 'Parch' 'Fare' 'Embarked']


In [27]:
ETC = ExtraTreesClassifier(n_estimators = 500, n_jobs = -1)

In [28]:
ETC.fit(x_zero_mean, y_val)
scores = cross_val_score(ETC, x_zero_mean, y_val, cv = 5)
print(scores)

[0.75977654 0.76966292 0.84269663 0.78089888 0.8258427 ]


In [29]:
print(ETC.feature_importances_)
print(ETC.feature_names_in_)

[0.10607274 0.28792338 0.24694502 0.04523319 0.04313951 0.23624065
 0.03444551]
['Pclass' 'Sex' 'Age' 'SibSp' 'Parch' 'Fare' 'Embarked']


In [30]:
df_test.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    0   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2          894       2                     Myles, Mr. Thomas Francis    0   
3          895       3                              Wirz, Mr. Albert    0   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   

    Age  SibSp  Parch   Ticket     Fare Cabin  Embarked  
0  34.5      0      0   330911   7.8292   NaN         0  
1  47.0      1      0   363272   7.0000   NaN         1  
2  62.0      0      0   240276   9.6875   NaN         0  
3  27.0      0      0   315154   8.6625   NaN         1  
4  22.0      1      1  3101298  12.2875   NaN         1

In [31]:
df_test_m= df_test.drop(['Name','Ticket','Cabin'], axis = 1)
df_test_m.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Sex          418 non-null    int64  
 3   Age          332 non-null    float64
 4   SibSp        418 non-null    int64  
 5   Parch        418 non-null    int64  
 6   Fare         417 non-null    float64
 7   Embarked     418 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 26.2 KB


In [32]:
df_test_m.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          892       3    0  34.5      0      0   7.8292         0
1          893       3    1  47.0      1      0   7.0000         1
2          894       2    0  62.0      0      0   9.6875         0
3          895       3    0  27.0      0      0   8.6625         1
4          896       3    1  22.0      1      1  12.2875         1

In [33]:
num_cols = list(df_test_m)
full_pipeline = ColumnTransformer([
    ("num", num_pipeline, num_cols)
])
df_test_final_n = full_pipeline.fit_transform(df_test_m)

In [34]:
df_test_final = pd.DataFrame(df_test_final_n, columns = df_test_m.columns, index = df_test_m.index)

In [35]:
df_train.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    0  22.0      1      0   7.2500       1.0
1            2         1       1    1  38.0      1      0  71.2833       3.0
2            3         1       3    1  26.0      0      0   7.9250       1.0
3            4         1       1    1  35.0      1      0  53.1000       1.0
4            5         0       3    0  35.0      0      0   8.0500       1.0

In [36]:
df_train_final.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          1.0       0.0     3.0  0.0  22.0    1.0    0.0   7.2500       1.0
1          2.0       1.0     1.0  1.0  38.0    1.0    0.0  71.2833       3.0
2          3.0       1.0     3.0  1.0  26.0    0.0    0.0   7.9250       1.0
3          4.0       1.0     1.0  1.0  35.0    1.0    0.0  53.1000       1.0
4          5.0       0.0     3.0  0.0  35.0    0.0    0.0   8.0500       1.0

In [37]:
def EnsembleGen(estimators, x_train, y_train, x_test):
    for e in estimators:
        e.fit(x_train, y_train)
    y_tests = []    
    for e in estimators:
        y_tests.append(e.predict(x_test))
    y_final = [] 
    for i in range (y_tests[0].size):
        sum = 0 
        for n in range (len(y_tests)):
            sum += y_tests[n][i]
        y_final.append(round(sum/len(y_tests)))
    return y_final   

In [38]:
x_trains, x_tests, y_trains, y_tests = train_test_split(x_val, y_val, test_size = 0.2, random_state = 42)

In [39]:
svc = SVC(kernel = 'linear', C = 1, probability = True)

In [40]:
estimators = [RFC, SGD_C, svc]
y_estimates = np.array(EnsembleGen(estimators, x_trains, y_trains, x_tests))

In [41]:
print(accuracy_score(y_estimates, y_tests))

0.7932960893854749


In [42]:
y_tests_1 = [(svc.predict_proba(x_trains)),(RFC.predict_proba(x_trains))]
print(y_tests_1)
print(y_tests_1[1][0][0])

[array([[0.81026922, 0.18973078],
       [0.81026979, 0.18973021],
       [0.81079626, 0.18920374],
       ...,
       [0.81260618, 0.18739382],
       [0.26256346, 0.73743654],
       [0.80928228, 0.19071772]]), array([[0.81168571, 0.18831429],
       [1.        , 0.        ],
       [0.64987063, 0.35012937],
       ...,
       [0.97333333, 0.02666667],
       [0.092     , 0.908     ],
       [0.884     , 0.116     ]])]
0.8116857142857143
